language: node_js
node_js: 10.15.1

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: ritwickdey@outlook.com
  api_key: $NPM_TOKEN
  name: Ritwick Dey
  on:
    tags: true